### ISSUE TITLE
Don't work with Sketch v52

### ISSUE THREAD

**Issue by mnogosmyslov** [MengTo/Angle-Sketch-Plugin#35]
Plugin don't work after update to Sketch 52.
I'm choose "Apply Mockup" command and nothing happens.
Please, fix it 
🙏

**Comment by ilustrebob** [comment]
Same problem here.

**Comment by Pererawolf57** [comment]
Confirmed too here ... I feel amputated :(

**Comment by tmergulhao** [comment]
Can you @Pererawolf57 @ilustrebob @mnogosmyslov test 1.1.3 of Angle?

Thanks!

**Comment by Pererawolf57** [comment]
Fixed ! Simply amazing and so reactive.

**Comment by ilustrebob** [comment]
Thanks a lot!

**Comment by pkiula** [comment]
Same problem here. Keeps showing me the error "Create an artboard"...

**Comment by mnogosmyslov** [comment]
@tmergulhao thanks a lot! Work stably!

**Comment by krachtstefan** [comment]
I just updated to 1.1.3 and it still doesn't react to Apply Mockup. I tried the shortcut and menu item and aslo restarted sketch after the update.

**Comment by mnogosmyslov** [comment]
@tmergulhao Sometimes paste flip horizontal image into mockup. It appears randomly.
Helps remove mockup and apply plugin again

**Comment by tmergulhao** [comment]
Hey @krachtstefan. Can you please contact support@designcode.io to provide more detail?

**Comment by tmergulhao** [comment]
Hey @mnogosmyslov. Can you please provide a video or GIF through dropbox (any service might work) link to support@designcode.io?

**Comment by mnogosmyslov** [comment]
@tmergulhao
http://take.ms/m3eGv

**Comment by evgenykvgl** [comment]
Hi! Angle plugin not work in Sketch 56.3. Support is not responding. How can I fix it?
